/**
 * redux 的 action 各种 type 
 */

const actionTypes = {

    // Fetching data type
    FETCH_DATA_TYPE_HOME: 'HOME',
    FETCH_DATA_TYPE_SYSTEM_TREE: 'SYSTEM_TREE',

    // Home Screen
    FETCH_HOME_DATA_START: 'FETCH_HOME_DATA_START',
    FETCH_HOME_BANNER: 'FETCH_HOME_BANNER',
    FETCH_HOME_TOP_ARTICLES: 'FETCH_HOME_TOP_ARTICLES',
    FETCH_HOME_ARTICLES: 'FETCH_HOME_ARTICLES',
    FETCH_HOME_ARTICLES_MORE: 'FETCH_HOME_ARTICLES_MORE',
    FETCH_HOME_ARTICLES_FAILURE: 'FETCH_HOME_ARTICLES_FAILURE',

    // System Screen
    FETCH_SYSTEM_TREE_START: 'FETCH_SYSTEM_TREE_START',
    FETCH_SYSTEM_TREE: 'FETCH_SYSTEM_TREE',
    FETCH_SYSTEM_TREE_FAILURE: 'FETCH_SYSTEM_TREE_FAILURE',

}

export default actionTypes